### ISSUE TITLE
Executable port

### ISSUE THREAD

**Issue by razvanab** [gaffe-buck/tavern-v2-character-creator#1]
Please consider making an executable alternative for this. It will be so much easier to use it instead of installing everything it requires to work.

**Comment by gaffe-buck** [comment]
Hi, Raz! Thanks for your feedback and I'm grateful folks are giving the app a try.

The security implications around providing a standalone executable for the app are outside of my risk tolerance. Since I no longer use windows, supporting a windows executable version would be burdensome and impractical.

**If you just want to use the app without installing anything, I suggest you try the github pages version** linked in the readme, which makes no external requests and only uses your browser's local storage to prevent loss of data if you close the tab. Here's the link: https://gaffe-buck.github.io/tavern-v2-character-creator/

Since I have no plans to include a standalone executable for this project, I will be closing this issue.

**Comment by razvanab** [comment]
I understand. Thank you.
